X_OFFSET: int = 147
Y_OFFSET: int = 260
COLUMN_WIDTH: int = 58
ROW_HEIGHT: int = 43
TABLES_DIFF: int = 335  # case when there are two tables on a picture
GROUPS: tuple[str, ...] = ('1.1', '1.2', '2.1', '2.2', '3.1', '3.2')
GROUP_COUNT: int = len(GROUPS)
HOUR_COUNT: int = 24
DATE_BOX: tuple[int, int, int, int] = 664, 0, 879, 71  # x_top, y_top, x_bottom, y_bottom
